// ==========================================
// FICHIER : 2_Sport.gs
// ==========================================

function syncSportsCalendarWithTransit() {
  Logger.log(`🏃 Synchronisation du planning sportif (${GLOBAL_CONFIG.SPORTS_SYNC_DAYS} jours)...`);

  const sportsCal = getOrCreateCalendar(GLOBAL_CONFIG.SPORTS_CAL_NAME);
  const schoolCal = getOrCreateCalendar(GLOBAL_CONFIG.SCHOOL_CAL_NAME);

  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const minStartDate = new Date(GLOBAL_CONFIG.SPORT_START_DATE + "T00:00:00");
  const effectiveStart = today < minStartDate ? minStartDate : today;
  const endDate = new Date(effectiveStart.getTime() + GLOBAL_CONFIG.SPORTS_SYNC_DAYS * 24 * 60 * 60 * 1000);

  const existingSportEvents = sportsCal.getEvents(today, endDate);
  const sportMap = new Map();
  
  existingSportEvents.forEach(ev => {
    const desc = ev.getDescription() || "";
    const match = desc.match(/🆔 SPORT_UID\s*:\s*([^\r\n]+)/);
    if (match) {
      sportMap.set(match[1].trim(), ev);
    }
    // Only manage events generated by the script, do NOT delete user's personal events
  });

  const neededSportUids = new Set();
  const allSchoolEvents = schoolCal.getEvents(today, endDate);
  const schoolByDate = groupEventsByDate_(allSchoolEvents);

  let totalCreated = 0;
  let totalUpdated = 0;
  let totalUnchanged = 0;

  const totalDays = Math.ceil((endDate.getTime() - effectiveStart.getTime()) / (24 * 60 * 60 * 1000));

  for (let d = 0; d < totalDays; d++) {
    const currentDate = new Date(effectiveStart.getTime() + d * 24 * 60 * 60 * 1000);
    const dayOfWeek = (currentDate.getDay() + 6) % 7; // 0=Lundi, ..., 6=Dimanche
    const dateKey = formatDateOnly(currentDate);

    const periodContext = getPeriodizationContext_(currentDate);

    if (dayOfWeek === 0) {
      const endOfWeek = new Date(currentDate.getTime() + 6 * 24 * 60 * 60 * 1000);
      Logger.log(`\n📅 ═══ CONFIGURATION SEMAINE du ${dateKey} au ${formatDateOnly(endOfWeek)} : ${periodContext.label} ═══`);
    }

    const rawSchoolEvents = schoolByDate.get(dateKey) || [];

    // Identification spécifique des cours selon le jour
    let chainedClass = null;

    if (dayOfWeek === 4) { // Vendredi : cours présentiel après-midi/soir
      chainedClass = rawSchoolEvents.find(ev => {
        const title = ev.getTitle().toUpperCase();
        const isPresentiel = !title.includes("DISTANCIEL") && !title.includes("TRAJET");
        const endH = ev.getEndTime().getHours();
        return isPresentiel && endH >= 15 && endH <= 19;
      }) || null;
    } else if (dayOfWeek === 5) { // Samedi : cours intensif (>=3.5h ou MTR801)
      chainedClass = rawSchoolEvents.find(ev => {
        const title = ev.getTitle().toUpperCase();
        const isPresentiel = !title.includes("DISTANCIEL") && !title.includes("TRAJET");
        const durHours = (ev.getEndTime().getTime() - ev.getStartTime().getTime()) / (3600 * 1000);
        return isPresentiel && (durHours >= 3.5 || title.includes("MTR801"));
      }) || null;
    }

    // Le dimanche a besoin de savoir si le samedi avait un cours intensif
    let saturdayHasIntensiveClass = false;
    const satDate = new Date(currentDate);
    if (dayOfWeek === 6) { // Dimanche : vérifier la veille (Samedi)
      satDate.setDate(satDate.getDate() - 1);
      const satKey = formatDateOnly(satDate);
      const satEvents = schoolByDate.get(satKey) || [];
      saturdayHasIntensiveClass = satEvents.some(ev => {
        const durHours = (ev.getEndTime().getTime() - ev.getStartTime().getTime()) / (3600 * 1000);
        return durHours >= 3.5 || ev.getTitle().toUpperCase().includes("MTR801");
      });
    } else if (dayOfWeek === 5) {
      saturdayHasIntensiveClass = Boolean(chainedClass);
    }

    const session = getDailyWorkoutPlan_(dayOfWeek, Boolean(chainedClass), saturdayHasIntensiveClass, periodContext, currentDate);
    const isRestDay = !session.address;

    let dayLastActivityEndTime = null;

    if (!isRestDay) {
      let workoutStart, workoutEnd, transitAllerMinutes, transitRetourMinutes;
      let startAddress = GLOBAL_CONFIG.HOME_ADDRESS;

      if (session.chainedAfterCourse && chainedClass) {
        const transitionMs = (GLOBAL_CONFIG.BUFFER_BETWEEN_CLASS_AND_SPORT_MIN || 10) * 60 * 1000;
        workoutStart = new Date(chainedClass.getEndTime().getTime() + transitionMs);
        workoutEnd = new Date(workoutStart.getTime() + session.duration * 60 * 1000);
        transitAllerMinutes = 0;
        startAddress = GLOBAL_CONFIG.ETS_ADDRESS;
        transitRetourMinutes = getMapsTravelMinutesCached(session.address, GLOBAL_CONFIG.HOME_ADDRESS, workoutEnd);
      } else {
        const targetHomeReturn = new Date(currentDate);
        targetHomeReturn.setHours(GLOBAL_CONFIG.TARGET_HOME_RETURN_HOUR, GLOBAL_CONFIG.TARGET_HOME_RETURN_MIN, 0, 0);

        const isHomeActivity = (session.address === GLOBAL_CONFIG.HOME_ADDRESS || session.locName.includes("Quartier") || session.locName.includes("Maison"));

        transitRetourMinutes = isHomeActivity ? 0 : getMapsTravelMinutesCached(session.address, GLOBAL_CONFIG.HOME_ADDRESS, targetHomeReturn);
        workoutEnd = new Date(targetHomeReturn.getTime() - transitRetourMinutes * 60 * 1000);
        workoutStart = new Date(workoutEnd.getTime() - session.duration * 60 * 1000);
        transitAllerMinutes = isHomeActivity ? 0 : getMapsTravelMinutesCached(GLOBAL_CONFIG.HOME_ADDRESS, session.address, workoutStart);
      }

      const travelAllerStart = new Date(workoutStart.getTime() - transitAllerMinutes * 60 * 1000);
      const travelRetourEnd = new Date(workoutEnd.getTime() + transitRetourMinutes * 60 * 1000);

      if (transitAllerMinutes > 0) {
        const allerUid = `SPORT_TRAVEL_ALLER_${dateKey}`;
        const allerTitle = `${CONFIG_RULES.SPORTS.TRAVEL.emoji} Trajet vers ${session.locName}`;
        const res = upsertSportEvent_(sportsCal, sportMap, neededSportUids, allerUid, allerTitle, travelAllerStart, workoutStart, {
          location: `${startAddress} ➔ ${session.address}`,
          description: `Trajet calculé : ~${transitAllerMinutes} min`,
          colorId: CONFIG_RULES.SPORTS.TRAVEL.colorId
        });
        totalCreated += res.created; totalUpdated += res.updated; totalUnchanged += res.unchanged;
      }

      const workoutUid = `SPORT_WORKOUT_${dateKey}`;
      const workoutTitle = `${session.emoji} ${session.title}`;
      const fullDescription = [
        `🏷️ Contexte : ${periodContext.label}`,
        `🎯 Séance : ${session.title}`,
        `📍 Lieu : ${session.locName}`,
        `⏱️ Durée : ${session.duration} min`,
        `\n📋 Protocole & Consignes :`,
        session.description
      ].join("\n");

      const wRes = upsertSportEvent_(sportsCal, sportMap, neededSportUids, workoutUid, workoutTitle, workoutStart, workoutEnd, {
        location: session.locName,
        description: fullDescription,
        colorId: session.colorId,
        chainedAfterCourse: session.chainedAfterCourse
      });
      totalCreated += wRes.created; totalUpdated += wRes.updated; totalUnchanged += wRes.unchanged;

      if (transitRetourMinutes > 0) {
        const retourUid = `SPORT_TRAVEL_RETOUR_${dateKey}`;
        const retourTitle = `${CONFIG_RULES.SPORTS.TRAVEL.emoji} Trajet Retour (${session.locName})`;
        const rRes = upsertSportEvent_(sportsCal, sportMap, neededSportUids, retourUid, retourTitle, workoutEnd, travelRetourEnd, {
          location: `${session.address} ➔ ${GLOBAL_CONFIG.HOME_ADDRESS}`,
          description: `Trajet retour : ~${transitRetourMinutes} min (Arrivée maison : ${formatTime(travelRetourEnd)})`,
          colorId: CONFIG_RULES.SPORTS.TRAVEL.colorId
        });
        totalCreated += rRes.created; totalUpdated += rRes.updated; totalUnchanged += rRes.unchanged;
      }

      dayLastActivityEndTime = travelRetourEnd;
    }

    let stretchStart = new Date(currentDate);
    stretchStart.setHours(22, 0, 0, 0);
    if (dayLastActivityEndTime && (dayLastActivityEndTime.getTime() + 15 * 60 * 1000 > stretchStart.getTime())) {
      stretchStart = new Date(dayLastActivityEndTime.getTime() + 15 * 60 * 1000);
    }

    const stretchEnd = new Date(stretchStart.getTime() + 20 * 60 * 1000);
    const stretchUid = `SPORT_STRETCH_${dateKey}`;
    const stretchTitle = `${CONFIG_RULES.SPORTS.MOBILITY.emoji} Étirements & Mobilité du soir`;
    const sRes = upsertSportEvent_(sportsCal, sportMap, neededSportUids, stretchUid, stretchTitle, stretchStart, stretchEnd, {
      description: "Pike/straddle stretch, lève-jambes assis, Jefferson curls, couch stretch.",
      colorId: CONFIG_RULES.SPORTS.MOBILITY.colorId
    });
    totalCreated += sRes.created; totalUpdated += sRes.updated; totalUnchanged += sRes.unchanged;

    if (dayOfWeek === 6 || d === totalDays - 1) {
      Logger.log(`✨ ── Semaine configurée avec succès (Jusqu'au ${dateKey}) ──\n`);
    }
  }

  let totalDeleted = 0;
  sportMap.forEach((ev, uid) => {
    if (!neededSportUids.has(uid)) {
      Logger.log(`  🗑️ [SPORT SUPPRIMÉ] ${ev.getTitle()} (${formatDate(ev.getStartTime())})`);
      ev.deleteEvent();
      totalDeleted++;
    }
  });

  Logger.log(`📊 BILAN SPORTIF GLOBAL : +${totalCreated} créés, ~${totalUpdated} modifiés, =${totalUnchanged} inchangés, -${totalDeleted} supprimés.`);
}

/**
 * Calculateur de périodisation avec rampe d'adaptation en septembre 2026
 */
function getPeriodizationContext_(date) {
  const planStart = new Date(GLOBAL_CONFIG.PLAN_START_DATE + "T00:00:00");
  const raceDay = new Date(GLOBAL_CONFIG.RACE_DATE + "T00:00:00");
  
  const diffFromStartDays = Math.floor((date.getTime() - planStart.getTime()) / (24 * 3600 * 1000));
  const daysToRace = Math.floor((raceDay.getTime() - date.getTime()) / (24 * 3600 * 1000));

  // --- AUTOMNE 2026 (Phase Fondation & Ramp-up Septembre) ---
  if (diffFromStartDays < 0) {
    const ramp1End = new Date("2026-09-07T00:00:00");
    const ramp2End = new Date("2026-09-14T00:00:00");
    const ramp3End = new Date("2026-09-21T00:00:00");

    if (date < ramp1End) {
      return { phase: "FONDATION_RAMP_1", weekNumber: 0, isDeload: false, volumeFactor: 0.55, label: "Phase Fondation : Ramp-up S1 (Adaptation ~55%)" };
    }
    if (date < ramp2End) {
      return { phase: "FONDATION_RAMP_2", weekNumber: 0, isDeload: false, volumeFactor: 0.75, label: "Phase Fondation : Ramp-up S2 (Montée ~75%)" };
    }
    if (date < ramp3End) {
      return { phase: "FONDATION_RAMP_3", weekNumber: 0, isDeload: false, volumeFactor: 0.90, label: "Phase Fondation : Ramp-up S3 (Consolidation ~90%)" };
    }
    return { phase: "FONDATION", weekNumber: 0, isDeload: false, volumeFactor: 0.85, label: "Phase Fondation (Plein régime Automne 2026)" };
  }

  // --- PLAN SPÉCIFIQUE QMT-80 (2027) ---
  if (daysToRace <= 6 && daysToRace >= 0) {
    return { phase: "RACE_WEEK", weekNumber: 24, isDeload: true, volumeFactor: 0.30, label: "Semaine de Course — QMT-80 🏁" };
  }

  const weekNumber = Math.floor(diffFromStartDays / 7) + 1;
  const weekInBlock = ((weekNumber - 1) % 4) + 1;
  const isDeload = (weekInBlock === 4);

  if (weekNumber <= 6) {
    return {
      phase: "PUISSANCE_HIVERNALE",
      weekNumber: weekNumber,
      isDeload: isDeload,
      volumeFactor: isDeload ? 0.70 : (0.80 + weekInBlock * 0.05),
      label: `S${weekNumber} [Puissance & Côtes] - ${isDeload ? '⚠️ Décharge' : 'Charge (' + weekInBlock + '/3)'}`
    };
  }

  if (weekNumber <= 16) {
    return {
      phase: "VOLUME_WEC_1",
      weekNumber: weekNumber,
      isDeload: isDeload,
      volumeFactor: isDeload ? 0.75 : (0.95 + weekInBlock * 0.05),
      label: `S${weekNumber} [Volume & WEC] - ${isDeload ? '⚠️ Décharge' : 'Charge (' + weekInBlock + '/3)'}`
    };
  }

  if (weekNumber <= 21) {
    return {
      phase: "SPECIFIQUE_PIC",
      weekNumber: weekNumber,
      isDeload: isDeload,
      volumeFactor: isDeload ? 0.75 : (1.10 + weekInBlock * 0.05),
      label: `S${weekNumber} [Pic Spécifique Mestashibo] - ${isDeload ? '⚠️ Décharge' : 'Charge (' + weekInBlock + '/3)'}`
    };
  }

  return {
    phase: "AFFUTAGE",
    weekNumber: weekNumber,
    isDeload: true,
    volumeFactor: weekNumber === 22 ? 0.65 : 0.45,
    label: `S${weekNumber} [Affûtage J-${daysToRace}]`
  };
}

/**
 * Matrice d'entraînement avec durées progressives et consignes physiologiques Strava (FCmax = 203 bpm)
 */
function getDailyWorkoutPlan_(dayOfWeek, hasEtsAfternoonClass, saturdayHasIntensiveClass, ctx, date) {
  const isDeload = ctx.isDeload;
  const setsNote = isDeload ? "(Décharge : 2 séries d'entretien, 0 échec)" : "(Charge : 4 séries de travail)";
  const month = date.getMonth(); 
  const isWinter = (month === 0 || month === 1 || month === 2);

  let durationMardi = Math.round(55 + (ctx.weekNumber * 1.5) * ctx.volumeFactor);
  let durationJeudi = Math.round(45 * ctx.volumeFactor);
  let durationSamediLong = Math.round((105 + (ctx.weekNumber * 4.5)) * ctx.volumeFactor);
  let durationDimanche = Math.round((60 + (ctx.weekNumber * 1.2)) * ctx.volumeFactor);

  // Calibrage spécifique pour la rampe de septembre et la fondation
  if (ctx.phase === "FONDATION_RAMP_1") {
    durationMardi = 45;
    durationJeudi = 35;
    durationSamediLong = 75;  // 1h15
    durationDimanche = 0;     // Repos complet en S1
  } else if (ctx.phase === "FONDATION_RAMP_2") {
    durationMardi = 50;
    durationJeudi = 40;
    durationSamediLong = 95;  // 1h35
    durationDimanche = 40;
  } else if (ctx.phase === "FONDATION_RAMP_3") {
    durationMardi = 55;
    durationJeudi = 45;
    durationSamediLong = 110; // 1h50
    durationDimanche = 50;
  } else if (ctx.phase === "FONDATION") {
    durationMardi = 60;
    durationJeudi = 50;
    durationSamediLong = 120; // 2h00
    durationDimanche = 65;
  }

  const renfoMardiMin = ctx.phase === "FONDATION_RAMP_1" ? 15 : 20;

  switch (dayOfWeek) {
    case 0: // Lundi
      return {
        title: "Calisthenics 1 (Push & Core)",
        duration: isDeload ? 45 : 65,
        locName: "ÉTS Gym",
        address: GLOBAL_CONFIG.ETS_ADDRESS,
        chainedAfterCourse: false,
        emoji: CONFIG_RULES.SPORTS.CALISTHENICS.emoji,
        colorId: CONFIG_RULES.SPORTS.CALISTHENICS.colorId,
        description: `• Dips : ${isDeload ? '2x6' : '4x6-8'}\n• Pike Push-ups / HSPU prog : ${isDeload ? '2x6' : '4x6'}\n• Pompes anneaux : ${isDeload ? '2x10' : '3x12'}\n• Core : Hollow body hold (3x45s), Levées de jambes suspendues.\n\n📌 ${setsNote}`
      };

    case 1: // Mardi (Côtes & D+ + Renforcement Bas du Corps)
      if (isWinter) {
        return {
          title: "Trail Indoor : D+ Tapis Incliné & Renfo Jambes (ÉTS Gym)",
          duration: durationMardi + renfoMardiMin,
          locName: "ÉTS Gym (Tapis D+ & Salle)",
          address: GLOBAL_CONFIG.ETS_ADDRESS,
          chainedAfterCourse: false,
          emoji: CONFIG_RULES.SPORTS.TRAIL_INTENSE.emoji,
          colorId: CONFIG_RULES.SPORTS.TRAIL_INTENSE.colorId,
          description: `❄️ SÉCURITÉ HIVER (Pas de glace/crampons) :\n• 15' échauffement tapis plat\n• Fractionné D+ Tapis 12-15 % (5.5 à 6.5 km/h) — Cible FC : 172-190 bpm (Zone 4/5)\n• Renforcement post-côtes (${renfoMardiMin} min) :\n  - Squats tempo descente 3s : ${isDeload ? '2x8' : '4x8'}\n  - Fentes bulgares : ${isDeload ? '2x8' : '3x10'}\n  - Mollets unilatéraux : ${isDeload ? '2x12' : '4x15'}`
        };
      }
      return {
        title: "Trail : Côtes D+ (Mont-Royal) + Renfo Jambes",
        duration: durationMardi + renfoMardiMin,
        locName: "Mont Royal",
        address: GLOBAL_CONFIG.MOUNT_ROYAL_ADDRESS,
        chainedAfterCourse: false,
        emoji: CONFIG_RULES.SPORTS.TRAIL_INTENSE.emoji,
        colorId: CONFIG_RULES.SPORTS.TRAIL_INTENSE.colorId,
        description: `• 15' V1 échauffement + ${isDeload ? '1 série de 5x 1\' côte' : '2 séries de (5x 1\' côte, r=descente souple)'} + 10' V1.\n• Cible montées : FC 172-190 bpm (Zone 4/5).\n• Renforcement post-côtes (${renfoMardiMin} min) : Fentes bulgares, squats tempo et mollets pour blinder les quadriceps à l'excentrique.`
      };

    case 2: // Mercredi
      return {
        title: "Calisthenics 2 (Pull & Core - Zéro jambes)",
        duration: isDeload ? 45 : 65,
        locName: "ÉTS Gym",
        address: GLOBAL_CONFIG.ETS_ADDRESS,
        chainedAfterCourse: false,
        emoji: CONFIG_RULES.SPORTS.GYM_FORCE.emoji,
        colorId: CONFIG_RULES.SPORTS.GYM_FORCE.colorId,
        description: `• Tractions strictes : ${isDeload ? '2x6' : '4x6-8'}\n• Muscle-up / progression : ${isDeload ? '2x3' : '4x3-5'}\n• Tirage horizontal / Front lever prog : ${isDeload ? '2x8' : '3x10'}\n• L-sit hold : 4x20s\n\n🛡️ Zéro impact jambes (Récupération post-mardi).`
      };

    case 3: // Jeudi (Footing Régénérant V1)
      return {
        title: "Running : Footing V1 Endurance Fondamentale",
        duration: durationJeudi,
        locName: "Quartier / Parc Maisonneuve",
        address: GLOBAL_CONFIG.HOME_ADDRESS,
        chainedAfterCourse: false,
        emoji: CONFIG_RULES.SPORTS.RUN_EASY.emoji,
        colorId: CONFIG_RULES.SPORTS.RUN_EASY.colorId,
        description: `• ${durationJeudi} min en aisance respiratoire stricte.\n• Cible Cardio : FC < 148 bpm (idéal 138-145 bpm, respiration 100% nasale possible).\n• Consigne Biomécanique : Garde une cadence élevée (170-175 pas/min) avec des foulées courtes et légères sous le bassin pour réactiver l'effet ressort et éviter les jambes lourdes.`
      };

    case 4: // Vendredi
      if (hasEtsAfternoonClass) {
        return {
          title: "Calisthenics 3 : Skills & Mobilité (Direct ÉTS Gym)",
          duration: 45,
          locName: "ÉTS Gym",
          address: GLOBAL_CONFIG.ETS_ADDRESS,
          chainedAfterCourse: true,
          emoji: CONFIG_RULES.SPORTS.CALISTHENICS.emoji,
          colorId: CONFIG_RULES.SPORTS.CALISTHENICS.colorId,
          description: "• Déverrouillage direct en salle à la sortie des cours.\n• Handstand hold, ouverture d'épaules et gainage."
        };
      }
      return {
        title: "Calisthenics 3 (Handstand & Skills)",
        duration: isDeload ? 40 : 60,
        locName: "ÉTS Gym",
        address: GLOBAL_CONFIG.ETS_ADDRESS,
        chainedAfterCourse: false,
        emoji: CONFIG_RULES.SPORTS.CALISTHENICS.emoji,
        colorId: CONFIG_RULES.SPORTS.CALISTHENICS.colorId,
        description: `• Handstand hold & équilibre libre (${isDeload ? '15 min' : '25 min'})\n• L-sit / V-sit : ${isDeload ? '2x15s' : '4x20s'}`
      };

    case 5: // Samedi (Sortie Longue Spécifique D+)
      if (saturdayHasIntensiveClass) {
        return {
          title: "Running : Décrassage V1 Tapis Gym (Direct ÉTS)",
          duration: 35,
          locName: "ÉTS Gym (Tapis)",
          address: GLOBAL_CONFIG.ETS_ADDRESS,
          chainedAfterCourse: true,
          emoji: CONFIG_RULES.SPORTS.RUN_EASY.emoji,
          colorId: CONFIG_RULES.SPORTS.RUN_EASY.colorId,
          description: "• 30-35 min sur tapis en salle au gym de l'ÉTS direct après le cours (Zone 1 très légère, FC < 142 bpm)."
        };
      }
      return {
        title: `Trail : Sortie Longue D+ (${Math.floor(durationSamediLong / 60)}h${(durationSamediLong % 60).toString().padStart(2, '0')})`,
        duration: durationSamediLong,
        locName: isWinter ? "Parc Maisonneuve / Voies déneigées" : "Mont Royal",
        address: isWinter ? GLOBAL_CONFIG.HOME_ADDRESS : GLOBAL_CONFIG.MOUNT_ROYAL_ADDRESS,
        chainedAfterCourse: false,
        emoji: CONFIG_RULES.SPORTS.TRAIL_LONG.emoji,
        colorId: CONFIG_RULES.SPORTS.TRAIL_LONG.colorId,
        description: `• Sortie pilier ultra-trail.\n• Cible Cardio : FC < 155 bpm (Zone 2 Endurance).\n• Consigne : Rando-course (marche active dès que la pente dépasse 8-10% pour préserver le cardio).\n• Nutrition à l'effort : 50-60g glucides/h + 500 mL électrolytes/h.`
      };

    case 6: // Dimanche (Back-to-Back ou Repos Ramp-up 1)
      if (ctx.phase === "FONDATION_RAMP_1") {
        return {
          title: "Repos & Récupération active (Ramp-up S1)",
          duration: 0,
          locName: "Maison",
          address: null, // Pas d'événement agenda créé
          chainedAfterCourse: false
        };
      }
      if (saturdayHasIntensiveClass) {
        return {
          title: `Trail : Sortie Longue D+ (${Math.floor(durationSamediLong / 60)}h${(durationSamediLong % 60).toString().padStart(2, '0')})`,
          duration: durationSamediLong,
          locName: isWinter ? "Parc Maisonneuve / Voies déneigées" : "Mont Royal",
          address: isWinter ? GLOBAL_CONFIG.HOME_ADDRESS : GLOBAL_CONFIG.MOUNT_ROYAL_ADDRESS,
          chainedAfterCourse: false,
          emoji: CONFIG_RULES.SPORTS.TRAIL_LONG.emoji,
          colorId: CONFIG_RULES.SPORTS.TRAIL_LONG.colorId,
          description: `• Sortie longue décalée au dimanche (retour maison à 13h00 pile).\n• Cible : FC < 155 bpm + nutrition 50-60g glucides/h.`
        };
      }
      return {
        title: `Trail : Sortie sur Fatigue / Vallonné (${durationDimanche} min)`,
        duration: durationDimanche,
        locName: isWinter ? "Quartier (Déneigé)" : "Mont Royal / Quartier",
        address: isWinter ? GLOBAL_CONFIG.HOME_ADDRESS : GLOBAL_CONFIG.MOUNT_ROYAL_ADDRESS,
        chainedAfterCourse: false,
        emoji: CONFIG_RULES.SPORTS.RUN_EASY.emoji,
        colorId: CONFIG_RULES.SPORTS.RUN_EASY.colorId,
        description: `• ${durationDimanche} min d'endurance fondamentale sur fatigue de la veille (effet Back-to-Back).\n• Cible Cardio : FC < 148 bpm stricte. Cadence dynamique 170-175 pas/min.`
      };

    default:
      return { title: "Rest Day", duration: 0, locName: "Maison", address: null };
  }
}

function upsertSportEvent_(sportsCal, sportMap, neededUids, uid, title, start, end, options) {
  neededUids.add(uid);
  const descWithUid = (options.description || "") + `\n\n🆔 SPORT_UID : ${uid}`;
  const existing = sportMap.get(uid);

  let reminders = [];
  if (uid.startsWith("SPORT_TRAVEL_ALLER_")) {
    reminders = GLOBAL_CONFIG.REMINDERS.DEPART_TRAJET;
  } else if (uid.startsWith("SPORT_WORKOUT_") && options.location && options.location.includes("Maisonneuve")) {
    reminders = GLOBAL_CONFIG.REMINDERS.FOOTING_MAISON;
  } else if (uid.startsWith("SPORT_WORKOUT_") && options.chainedAfterCourse) {
    reminders = GLOBAL_CONFIG.REMINDERS.CHAINED_SPORT;
  } else if (uid.startsWith("SPORT_STRETCH_")) {
    reminders = GLOBAL_CONFIG.REMINDERS.MOBILITE_SOIR;
  }

  function applyReminders(ev) {
    ev.removeAllReminders();
    reminders.forEach(min => ev.addPopupReminder(min));
  }

  if (existing) {
    const titleMatch = existing.getTitle() === title;
    const timeMatch = existing.getStartTime().getTime() === start.getTime() &&
                      existing.getEndTime().getTime() === end.getTime();
    
    if (titleMatch && timeMatch) {
      applyReminders(existing);
      return { created: 0, updated: 0, unchanged: 1 };
    }

    Logger.log(`  ✏️ [SPORT MODIFIÉ] ${title} (${formatDate(start)})`);
    existing.setTitle(title);
    existing.setTime(start, end);
    existing.setDescription(descWithUid);
    if (options.location) existing.setLocation(options.location);
    if (options.colorId) existing.setColor(options.colorId);
    applyReminders(existing);
    return { created: 0, updated: 1, unchanged: 0 };
  }

  Logger.log(`  ➕ [SPORT AJOUTÉ] ${title} (${formatDate(start)})`);
  const ev = sportsCal.createEvent(title, start, end, {
    location: options.location || "",
    description: descWithUid
  });
  if (options.colorId) ev.setColor(options.colorId);
  applyReminders(ev);
  sportMap.set(uid, ev);
  return { created: 1, updated: 0, unchanged: 0 };
}